mode: Mainline
branches:
  master:
    tag: ''
    increment: inherit
    source-branches:
      - master
    is-release-branch: true
  feature:
    mode: ContinuousDeployment
    increment: Minor
    tag: alpha
  release:
    mode: ContinuousDeployment
    increment: Major
    tag: beta
    is-release-branch: false
  hotfix:
    mode: ContinuousDeployment
    increment: Patch
    tag: beta
ignore:
  sha: [ ]