mode: Mainline
branches:
  feature:
    mode: ContinuousDeployment
    increment: Minor
  release:
    mode: ContinuousDeployment
    increment: Major
    is-release-branch: false
  hotfix:
    mode: ContinuousDeployment
    increment: Patch
ignore:
  sha: [ ]