name: build-test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment variables
        id: dotenv
        uses: falti/dotenv-action@v0.2.8  

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Check out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build ${{ steps.dotenv.outputs.project_name }}.sln --configuration release --no-restore

      - name: Run Tests
        run: dotnet test ${{ steps.dotenv.outputs.project_name }}.sln --configuration Release --no-build --verbosity normal