name: build-test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Junetic.Common
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Check out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Restore dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build ${{ env.PROJECT_NAME }}.sln --configuration release --no-restore

      - name: Run Tests
        run: dotnet test ${{ env.PROJECT_NAME }}.sln --configuration Release --no-build --verbosity normal